; Generated by calcit ffi-bindgen preview from Interface IR v1. Do not edit.
; Package: calcit.std 0.2.29

ns generated.calcit.std.ffi

defn md5$raw (dylib-path arg0)
  &call-dylib-edn dylib-path |md5 arg0
