// Generated by calcit ffi-bindgen preview from Interface IR v2. Do not edit.
// Package: calcit.std 0.2.29

pub trait CalcitStdFfi {
  fn md5(&self, arg0: String) -> Result<String, String>;
}

pub fn md5_calcit_adapter(_args: Vec<cirru_edn::Edn>) -> Result<cirru_edn::Edn, String> {
  todo!("decode edn-buffer-v1 arguments and invoke typed CalcitStdFfi::md5")
}

calcit_native_ffi::export_edn_buffer_method_v1!(md5_calcit_ffi_v1, md5_calcit_adapter);
