{} (:about "|Per-backend exclusions for scripts/run-core-tests.mjs. Keys under :tests are test ids (namespace/definition#name); :tags maps a test tag to a reason. Every reason starts with a category: unsupported (the backend explicitly rejects the construct), parity (the backend disagrees with native; fix in a separate issue), host (needs a host capability the replay does not provide), replay (an artifact of replaying outside the owning namespace).")
  :native $ {}
  :js $ {}
    :tests $ {} (|calcit.core/deftrait#requires-head-accepts-bare-and-quoted "|parity: JS codegen cannot emit the raw `macroexpand` syntax node used by this test")
  :wasm $ {}
    :tags $ {} $ :enum-definition-equality "|unsupported: first-class EnumDef creation requires &enum-def:new, rejected by WASM codegen (#1863)"
    :tests $ {} (|calcit.core/&+#preserves-primitive-schema-in-local-binding "|unsupported: unsupported WASM expression: (&proc &+)")
      |calcit.core/&core-string-methods#excludes-file-effects "|unsupported: unsupported proc in WASM: &methods-of"
      |calcit.core/&doseq#applies-side-effects-per-item "|unsupported: unsupported proc in WASM: ref"
      |calcit.core/&doseq#types-range-index-in-body "|unsupported: unsupported proc in WASM: ref"
      |calcit.core/&enum:definition#nominal-definition-evidence "|unsupported: E_WASM_NIL_TYPE_EVIDENCE: `calcit.core/impl-traits` requires concrete argument types so nil can be distinguished from false and 0 (imported value …"
      |calcit.core/&extract-code-into-edn#rejects-runtime-only-values "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/&list:apply#preserves-homogeneous-function-result-types "|unsupported: nested fn/defn closure values are not yet supported in WASM codegen"
      |calcit.core/&list:assoc#rejects-out-of-range-index "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/&list:filter-pair#filters-key-value-pairs "|unsupported: E_WASM_CLOSURE_SPECIALIZATION: `calcit.core/&list:filter-pair` argument 2 is a closure but its static parameter contract is not callable"
      |calcit.core/&list:flatten#flattens-nested-lists-and-sets "|parity: collection result differs from native (assert= fails on the heap values)"
      |calcit.core/&list:map#typed-empty-accumulator "|parity: collection result differs from native (assert= fails on the heap values)"
      |calcit.core/&list:map-pair#maps-key-value-pairs "|unsupported: E_WASM_CLOSURE_SPECIALIZATION: `calcit.core/&list:map-pair` argument 2 is a closure but its static parameter contract is not callable"
      |calcit.core/&list:map-pair#uses-strict-named-call "|unsupported: E_WASM_CLOSURE_SPECIALIZATION: `calcit.core/&list:map-pair` argument 2 is a closure but its static parameter contract is not callable"
      |calcit.core/&list:nth#rejects-non-integer-index "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/&list:slice#rejects-fractional-bounds "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/&map:destruct#exposes-pairs-and-folds "|unsupported: traps in unsupported dependency `calcit.core/count`: E_WASM_TRAIT_TYPE_EVIDENCE: &trait-call requires a concrete receiver type"
      |calcit.core/&map:filter-kv#filters-map-keys-and-values "|unsupported: unsupported proc in WASM: &map:fold-kv"
      |calcit.core/&map:filter-kv#preserves-typed-fields-and-effects "|unsupported: unsupported proc in WASM: ref"
      |calcit.core/&map:map#maps-map-pairs-directly "|parity: collection result differs from native (assert= fails on the heap values)"
      |calcit.core/&map:map#maps-pair-callback-with-key-and-value "|unsupported: unsupported proc in WASM: &map:fold-kv"
      |calcit.core/&map:map-list#maps-map-pairs-to-list "|parity: collection result differs from native (assert= fails on the heap values)"
      |calcit.core/&number:display-by#rejects-out-of-domain-values "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/&number:format#formats-decimal-places "|unsupported: unsupported proc in WASM: &number:format"
      |calcit.core/&number:format#rejects-digits-past-100 "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/&number:format#rounds-ties-away-from-zero "|unsupported: unsupported proc in WASM: &number:format"
      |calcit.core/&number:rem#rejects-zero-and-non-safe-integers "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/&str:escape#escapes-quoted-strings "|parity: wrong result: expected \"a \\\"\", got a \""
      |calcit.core/&str:pad-left#bounds-the-target-length "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/&str:pad-right#bounds-the-target-length "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/&str:slice#scalar-slice-invalid-evaluation "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/Option#direct-construction-preserves-value-and-failure "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/Option#matches-payloads-and-rejects-arity-mismatch "|parity: wrong result: expected 37, got 5"
      |calcit.core/Result#direct-construction-preserves-value-and-failure "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/add-watch!#registers-once-and-preserves-callback-order "|unsupported: unsupported proc in WASM: ref"
      |calcit.core/and#short-circuit-and-original-value-identity "|unsupported: unsupported proc in WASM: ref"
      |calcit.core/apply#preserves-evaluation-order "|unsupported: unsupported proc in WASM: ref"
      |calcit.core/apply#preserves-statement-evaluation-order "|unsupported: unsupported proc in WASM: ref"
      |calcit.core/apply#spreads-list-arguments "|parity: traps (unreachable) at runtime; native passes"
      |calcit.core/assert-type#proven-list-payload "|parity: wrong result: expected 3, got 0"
      |calcit.core/assoc#preserves-struct-through-option-match "|unsupported: unsupported proc in WASM: &struct-def:new"
      |calcit.core/assoc#rejects-non-number-list-index "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/assoc-in#assocs-nested-maps-lists-and-nil-base "|unsupported: E_WASM_NIL_TYPE_EVIDENCE: nil? cannot distinguish nil from false or 0 for open type `dynamic`"
      |calcit.core/bit-and#rejects-non-i32-operands "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/case#literal-match-evaluates-once "|unsupported: unsupported proc in WASM: ref"
      |calcit.core/case-default#literal-patterns-use-match "|parity: wrong result: expected b, got n"
      |calcit.core/char-from-code#rejects-invalid-scalars "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/concat-dynamic#joins-open-lists "|parity: wrong result: expected 3, got 0"
      |calcit.core/contains-field?#checks-tag-field-and-missing-field "|unsupported: unsupported proc in WASM: &struct-def:new"
      |calcit.core/contains-in?#traverses-maps-lists-tags-and-enums "|parity: codegen fails: ::: expected tag as first arg, got: ([] (&syntax quote) 'quote)"
      |calcit.core/contains?#rejects-non-number-list-index "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/count#empty-and-collection-counts "|parity: wrong result: expected 2, got 3"
      |calcit.core/data-view#classifies-symbol-struct-ref "|unsupported: unsupported runtime quote value in WASM"
      |calcit.core/data-view#classifies-values "|unsupported: E_WASM_NIL_TYPE_EVIDENCE: `calcit.core/data-view` requires concrete argument types so nil can be distinguished from false and 0"
      |calcit.core/data-view#exhaustive-view "|unsupported: E_WASM_NIL_TYPE_EVIDENCE: `calcit.core/data-view` requires concrete argument types so nil can be distinguished from false and 0"
      |calcit.core/data-view#lowered-match-agrees-with-enum-path "|unsupported: unsupported runtime quote value in WASM"
      |calcit.core/data-view#preserves-shallow-payloads "|unsupported: E_WASM_NIL_TYPE_EVIDENCE: `calcit.core/data-view` requires concrete argument types so nil can be distinguished from false and 0"
      |calcit.core/dbg#evaluates-once "|unsupported: unsupported proc in WASM: ref"
      |calcit.core/decode-map-as#decodes-inside-typed-first "|unsupported: decode-map-as is not yet supported in WASM codegen"
      |calcit.core/decode-map-as#preserves-operation-and-nested-error-path "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/ffi-response:resolve#method-preserves-capability-error "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/ffi-response:reject#method-preserves-capability-error "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/decode-map-as#decodes-struct-and-option "|unsupported: decode-map-as is not yet supported in WASM codegen"
      |calcit.core/decode-map-as#nested-struct-option "|unsupported: decode-map-as is not yet supported in WASM codegen"
      |calcit.core/decode-map-as#preserves-dynamic-and-prewrapped-option "|unsupported: decode-map-as is not yet supported in WASM codegen"
      |calcit.core/defstruct#local-definition-constructs-directly "|unsupported: unsupported proc in WASM: &struct-def:new"
      |calcit.core/deftrait#requires-head-accepts-bare-and-quoted "|unsupported: unsupported syntax in WASM: macroexpand"
      |calcit.core/deref#named-call-preserves-ref-payload "|unsupported: unsupported proc in WASM: ref"
      |calcit.core/destruct-map#splits-entry-and-remainder "|parity: collection result differs from native (assert= fails on the heap values)"
      |calcit.core/dissoc#empty-list-spread-keeps-map "|parity: codegen emits a module the engine rejects: Compiling function #65 failed: expected 1 elements on the stack for fallthru, found 2"
      |calcit.core/dissoc#explicitly-converts-set-keys "|parity: collection result differs from native (assert= fails on the heap values)"
      |calcit.core/dissoc#fixed-call-direct-evaluates-arguments-once "|unsupported: unsupported proc in WASM: ref"
      |calcit.core/dissoc#fixed-call-spread-evaluates-arguments-once "|unsupported: unsupported proc in WASM: ref"
      |calcit.core/dissoc#local-function-list-spread "|parity: traps (unreachable) at runtime; native passes"
      |calcit.core/dissoc#preserves-heterogeneous-list-spread "|parity: collection result differs from native (assert= fails on the heap values)"
      |calcit.core/dissoc#preserves-unspread-arguments "|parity: codegen emits a module the engine rejects: Compiling function #65 failed: expected 1 elements on the stack for fallthru, found 2"
      |calcit.core/dissoc#rejects-unsupported-receiver "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/dissoc#removes-list-index-by-kind-dispatch "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/dissoc#removes-multiple-map-keys "|parity: collection result differs from native (assert= fails on the heap values)"
      |calcit.core/dissoc#spreads-list-keys "|parity: collection result differs from native (assert= fails on the heap values)"
      |calcit.core/dissoc#supports-multiple-list-spreads "|parity: collection result differs from native (assert= fails on the heap values)"
      |calcit.core/dissoc-in#dissocs-nested-maps-and-list-indexes "|unsupported: E_WASM_NIL_TYPE_EVIDENCE: `calcit.core/assoc` requires concrete argument types so nil can be distinguished from false and 0"
      |calcit.core/do#supports-multiple-fn-body-without-do "|unsupported: unsupported proc in WASM: ref"
      |calcit.core/do#supports-multiple-let-body-without-do "|unsupported: unsupported proc in WASM: ref"
      |calcit.core/ffi-task:cancel#checked-unit-preserves-actual-value "|unsupported: decode-map-as is not yet supported in WASM codegen"
      |calcit.core/ffi-task:cancel#checked-unit-rejects-nil "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/ffi-task:cancel#checked-unit-rejects-number "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/ffi-task:cancel#checked-unit-rejects-string "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/ffi-task:cancel#default-method-preserves-capability-error "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/ffi-task:cancel-with#explicit-method-preserves-capability-error "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/ffi-task:cancel-with#reason-error-propagates-before-host-call "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/ffi-task:cancel-with#reason-evaluates-once-before-host-error "|unsupported: unsupported proc in WASM: ref"
      |calcit.core/ffi:response#effect-method-contract "|unsupported: E_WASM_CLOSURE_SPECIALIZATION: closure `resolve` escapes a statically specialized call"
      |calcit.core/ffi:task#effect-method-contract "|unsupported: E_WASM_CLOSURE_SPECIALIZATION: closure `cancel` escapes a statically specialized call"
      |calcit.core/filter-map-kv#preserves-captured-generic-relations "|unsupported: reaches `calcit.core/to-tag`: E_WASM_TAG_CONVERSION: turn-tag/to-tag requires runtime tag interning, which WASM does not support"
      |calcit.core/filter-map-kv#preserves-collision-iterator-last-value "|unsupported: unsupported proc in WASM: &map:fold-kv"
      |calcit.core/filter-map-kv#preserves-generic-callback-map-types "|unsupported: reaches `calcit.core/to-tag`: E_WASM_TAG_CONVERSION: turn-tag/to-tag requires runtime tag interning, which WASM does not support"
      |calcit.core/filter-map-kv#skips-empty-and-propagates-failure "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/fold#receiver-method "|parity: wrong result: expected 6, got 0"
      |calcit.core/fold-while#stops-calling-reducer-after-break "|unsupported: unsupported proc in WASM: ref"
      |calcit.core/foldl-compare#typed-number-exits "|unsupported: recur in a statically specialized closure is not yet supported in WASM codegen"
      |calcit.core/foldl-shortcut#returns-shortcut-accumulator "|parity: codegen fails: ::: expected tag as first arg, got: ([] (&proc &=) 'x 2)"
      |calcit.core/foldr-shortcut#returns-shortcut-accumulator "|parity: codegen fails: ::: expected tag as first arg, got: ([] (&proc &=) 'x 2)"
      |calcit.core/format-cirru#formats-nested-lines "|unsupported: unsupported proc in WASM: format-cirru"
      |calcit.core/format-cirru-edn#formats-basic-edn-values "|unsupported: unsupported runtime quote value in WASM"
      |calcit.core/format-cirru-one-liner#formats-simple-form-on-one-line "|unsupported: unsupported proc in WASM: format-cirru-one-liner"
      |calcit.core/format-cirru-one-liner#rejects-spread-non-list "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/format-to-lisp#distinguishes-simple-and-quoted-strings "|unsupported: unsupported runtime format-to-lisp in WASM: requires a statically quoted expression"
      |calcit.core/format-to-lisp#formats-runtime-number "|unsupported: unsupported runtime format-to-lisp in WASM: requires a statically quoted expression"
      |calcit.core/fs:path#fs-path-contract "|unsupported: reaches `calcit.core/fs-path:write-text`: E_WASM_CAPABILITY: filesystem writes are unavailable for the core WASM target"
      |calcit.core/fs:path#write-text-effect-contract "|unsupported: reaches `calcit.core/fs-path:write-text`: E_WASM_CAPABILITY: filesystem writes are unavailable for the core WASM target"
      |calcit.core/get#reads-runtime-struct-from-open-value "|unsupported: unsupported runtime quote value in WASM"
      |calcit.core/get#reads-tag-keys-via-postfix "|unsupported: unsupported method in WASM: .a"
      |calcit.core/get#typed-nested-get-inside-when "|unsupported: unsupported proc in WASM: ref"
      |calcit.core/get-args#returns-strings "|unsupported: reaches `calcit.core/get-args`: E_WASM_CAPABILITY: process arguments are unavailable for the core WASM target"
      |calcit.core/get-char-code#rejects-multiple-characters "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/get-env#missing-env-keeps-nominal-string-option "|host: needs the io.get_env import; the replay host only provides io.log_* and math (env ABI is covered by scripts/test-wasm.mjs)"
      |calcit.core/get-env#present-env-preserves-text-and-absence "|host: needs the io.get_env import; the replay host only provides io.log_* and math (env ABI is covered by scripts/test-wasm.mjs)"
      |calcit.core/get-in#reads-nested-open-map-payload "|unsupported: E_WASM_NIL_TYPE_EVIDENCE: `calcit.core/get-in` requires concrete argument types so nil can be distinguished from false and 0"
      |calcit.core/group-by#groups-list-by-derived-key "|parity: codegen fails: inline closure expects 2 argument(s), got 1"
      |calcit.core/hint-fn#async-tail-return-contract "|unsupported: E_WASM_CLOSURE_SPECIALIZATION: closure `forward` escapes a statically specialized call"
      |calcit.core/hint-fn#callable-return-contract "|unsupported: unsupported call head in WASM: ([] 'keep 'pass-number)"
      |calcit.core/hint-fn#checked-number-to-concrete-call "|unsupported: try-decode-map-as is not yet supported in WASM codegen"
      |calcit.core/hint-fn#literal-spread-call-contract "|parity: codegen fails: F64Add expects 2 args, got 1"
      |calcit.core/hint-fn#open-element-classified-before-payload "|unsupported: E_WASM_NIL_TYPE_EVIDENCE: calcit.core/data-view requires concrete argument types so nil can be distinguished from false and 0"
      |calcit.core/hint-fn#raise-only-return-contract "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/if#condition-and-selected-branch-errors-propagate "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/if#condition-evaluates-once-and-only-one-branch-runs "|unsupported: unsupported proc in WASM: ref"
      |calcit.core/if#direct-unsafe-bool-keeps-runtime-truthiness "|unsupported: E_WASM_UNSUPPORTED_JS_FFI: unsafe-coerce cannot preserve value identity in the current scalar WASM ABI"
      |calcit.core/includes?#checks-open-map-values-and-set-members "|unsupported: E_WASM_TRAIT_TYPE_EVIDENCE: a List mixing Map and Set receivers has no concrete element type for the open includes? dispatch"
      |calcit.core/join-string#renders-numbers-duplicates-and-empty-list "|parity: wrong result: expected 1-2-3, got 1-1-1"
      |calcit.core/keys-non-nil#omits-nil-map-values "|unsupported: E_WASM_CALL_SPECIALIZATION: recursive specialization of `calcit.core/&section-by-loop` is not supported"
      |calcit.core/last#rejects-invalid-string-indices "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/loop#preserves-standalone-loop-effects "|unsupported: unsupported proc in WASM: ref"
      |calcit.core/map#maps-map-pairs "|parity: collection result differs from native (assert= fails on the heap values)"
      |calcit.core/map-entries#infers-sort-comparator-fields "|unsupported: reaches `calcit.core/map-entries`: unsupported proc in WASM: &map:fold-kv"
      |calcit.core/map-entries#preserves-key-value-types "|unsupported: reaches `calcit.core/map-entries`: unsupported proc in WASM: &map:fold-kv"
      |calcit.core/map-entries#survives-sort-and-indexing "|unsupported: reaches `calcit.core/map-entries`: unsupported proc in WASM: &map:fold-kv"
      |calcit.core/map-indexed#preserves-open-payload-with-index "|parity: collection result differs from native (assert= fails on the heap values)"
      |calcit.core/map-kv#skips-nil-results "|replay: WASM replays from a separate namespace, where the calcit.core-only map-kv compatibility exemption does not apply (E_MAP_KV_UNPROVEN_CONTRACT)"
      |calcit.core/map-kv#transforms-each-entry "|replay: WASM replays from a separate namespace, where the calcit.core-only map-kv compatibility exemption does not apply (E_MAP_KV_UNPROVEN_CONTRACT)"
      |calcit.core/map-list-kv#collects-typed-key-value-results "|unsupported: unsupported proc in WASM: &map:fold-kv"
      |calcit.core/map-list-kv#preserves-iteration-effects-and-failure "|unsupported: unsupported proc in WASM: ref"
      |calcit.core/map-list-kv#preserves-nominal-key-value-fields "|unsupported: unsupported proc in WASM: &map:fold-kv"
      |calcit.core/mapcat#flat-map-keeps-order-type-and-callback-count "|unsupported: unsupported proc in WASM: ref"
      |calcit.core/merge#combines-maps-left-to-right "|unsupported: E_WASM_CALL_SPECIALIZATION: recursive specialization of `calcit.core/&section-by-loop` is not supported"
      |calcit.core/merge-non-nil#keeps-existing-values-for-nil "|unsupported: E_WASM_CALL_SPECIALIZATION: recursive specialization of `calcit.core/&section-by-loop` is not supported"
      |calcit.core/monotonic-time-ms#keeps-monotonic-milliseconds "|unsupported: E_WASM_CAPABILITY: monotonic-time-ms is unavailable for the core WASM target"
      |calcit.core/number->int8#checks-boundaries-and-type "|unsupported: parse-cirru-edn-as is not yet supported in WASM codegen"
      |calcit.core/option:let#short-circuits-none "|replay: outside calcit.core the expanded `.and-then` receiver resolves to Dynamic (E_DYNAMIC_METHOD_DISPATCH)"
      |calcit.core/or#short-circuit-and-original-value-identity "|unsupported: unsupported proc in WASM: ref"
      |calcit.core/parse-cirru#returns-cirru-quote-tree "|unsupported: unsupported proc in WASM: parse-cirru"
      |calcit.core/parse-cirru-edn#parses-enums-comments-and-quoted-code "|unsupported: unsupported proc in WASM: parse-cirru-edn"
      |calcit.core/parse-cirru-list#returns-nested-text-lines "|unsupported: unsupported proc in WASM: parse-cirru-list"
      |calcit.core/parse-float#parses-nonfinite-spellings "|unsupported: reaches `calcit.core/parse-float`: E_WASM_NIL_TYPE_EVIDENCE: nil? cannot distinguish nil from a zero-valued Optional<:number> payload in the current …"
      |calcit.core/parse-float#reports-invalid-number-source "|unsupported: reaches `calcit.core/parse-float`: E_WASM_NIL_TYPE_EVIDENCE: nil? cannot distinguish nil from a zero-valued Optional<:number> payload in the current …"
      |calcit.core/parse-float#result-method-contract "|unsupported: reaches `calcit.core/parse-float`: E_WASM_NIL_TYPE_EVIDENCE: nil? cannot distinguish nil from a zero-valued Optional<:number> payload in the current …"
      |calcit.core/parse-float#wraps-number-or-source-error "|unsupported: reaches `calcit.core/parse-float`: E_WASM_NIL_TYPE_EVIDENCE: nil? cannot distinguish nil from a zero-valued Optional<:number> payload in the current …"
      |calcit.core/quote#function-tail-values "|unsupported: unsupported runtime quote value in WASM"
      |calcit.core/quote#nested-tail-and-expression-contexts "|unsupported: unsupported runtime quote value in WASM"
      |calcit.core/quote#preserves-non-evaluation-and-effects "|unsupported: unsupported proc in WASM: ref"
      |calcit.core/range#handles-negative-fractional-and-overflow "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/range#rejects-oversized-length "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/range#rejects-zero-step "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/range-bothway#creates-symmetric-and-offset-ranges "|parity: collection result differs from native (assert= fails on the heap values)"
      |calcit.core/read-dir#preserves-missing-directory-failure "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/read-dir#preserves-one-and-two-argument-directory-reads "|parity: codegen fails: unknown function: calcit.core/read-dir"
      |calcit.core/read-file#preserves-file-read-alias "|parity: codegen fails: unknown function: calcit.core/read-file"
      |calcit.core/read-file#preserves-missing-file-failure "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/reduce#reduces-list-from-initial-value "|parity: wrong result: expected 14, got 2"
      |calcit.core/ref#creates-typed-local-ref "|unsupported: unsupported proc in WASM: ref"
      |calcit.core/remove-watch!#rejects-missing-key-without-repeating-effect "|unsupported: unsupported proc in WASM: ref"
      |calcit.core/recur#recurs-from-try-and-match-tail-positions "|unsupported: unsupported syntax in WASM: try; the match assertion is also replayed separately by recurs-from-match-tail-position"
      |calcit.core/result:map-err#typed-method-selects-only-matching-branch "|unsupported: reaches `calcit.core/to-tag`: E_WASM_TAG_CONVERSION: runtime tag interning is unsupported; maps-error-to-inferred-number replays the supported method path"
      |calcit.core/rest#rejects-non-sequence "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/reset!#empty-initializer-needs-explicit-payload "|unsupported: unsupported proc in WASM: ref"
      |calcit.core/reset!#nested-assignment-returns-final-value "|unsupported: unsupported proc in WASM: ref"
      |calcit.core/reset!#returns-assigned-scalar "|unsupported: unsupported proc in WASM: ref"
      |calcit.core/chunks#splits-list-into-fixed-sections "|unsupported: E_WASM_CALL_SPECIALIZATION: recursive specialization of `calcit.core/&section-by-loop` is not supported"
      |calcit.core/chunks#keeps-short-lists-whole "|unsupported: E_WASM_CALL_SPECIALIZATION: recursive specialization of `calcit.core/&section-by-loop` is not supported"
      |calcit.core/chunks#empty-list-has-no-sections "|unsupported: E_WASM_CALL_SPECIALIZATION: recursive specialization of `calcit.core/&section-by-loop` is not supported"
      |calcit.core/section-by#forwards-to-chunks "|unsupported: E_WASM_CALL_SPECIALIZATION: recursive specialization of `calcit.core/&section-by-loop` is not supported"
      |calcit.core/secure-random-bytes#rejects-invalid-length "|unsupported: reaches `calcit.core/secure-random-bytes`: E_WASM_CAPABILITY: secure-random-bytes is unavailable for the core WASM target"
      |calcit.core/secure-random-bytes#returns-buffer "|unsupported: reaches `calcit.core/secure-random-bytes`: E_WASM_CAPABILITY: secure-random-bytes is unavailable for the core WASM target"
      |calcit.core/sort#orders-list-with-default-comparator "|unsupported: &list:sort in WASM requires a list and an explicit 2-argument comparator"
      |calcit.core/sort#sorts-nan-after-numbers "|unsupported: &list:sort in WASM requires a list and an explicit 2-argument comparator"
      |calcit.core/starts-with?#supports-tag-and-string-prefixes "|replay: outside calcit.core the test's bare unsafe-coerce is rejected (E_UNSCOPED_UNSAFE_COERCE)"
      |calcit.core/str#omits-nil-and-renders-enums "|parity: wrong result: expected (%:: _ :a |世界 \"|海 洋\"), got (:: :a |世界 \"|海 洋\")"
      |calcit.core/swap!#expanded-result-is-the-assigned-value "|unsupported: unsupported proc in WASM: ref"
      |calcit.core/to-lispy-string#distinguishes-display-from-lisp-format "|unsupported: unsupported runtime format-to-lisp in WASM: requires a statically quoted expression"
      |calcit.core/to-string#converts-finite-scalars "|unsupported: reaches `calcit.core/to-symbol`: unsupported proc in WASM: turn-symbol"
      |calcit.core/to-string#map-entry-tag-method-contract "|unsupported: nested fn/defn closure values are not yet supported in WASM codegen"
      |calcit.core/to-string#scalar-method-contract "|unsupported: reaches `calcit.core/to-symbol`: unsupported proc in WASM: turn-symbol"
      |calcit.core/to-symbol#converts-string-to-symbol "|unsupported: reaches `calcit.core/to-symbol`: unsupported proc in WASM: turn-symbol"
      |calcit.core/to-tag#converts-string-to-tag "|unsupported: reaches `calcit.core/to-tag`: E_WASM_TAG_CONVERSION: turn-tag/to-tag requires runtime tag interning, which WASM does not support"
      |calcit.core/try#passes-error-message-to-handler "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/try#returns-body-on-success "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/try-decode-map-as#decoded-ref-keeps-original-alias-open "|unsupported: unsupported proc in WASM: ref"
      |calcit.core/try-decode-map-as#parsed-open-value-deep-rejection "|unsupported: try-decode-map-as is not yet supported in WASM codegen"
      |calcit.core/try-decode-map-as#parsed-open-value-deep-success "|unsupported: try-decode-map-as is not yet supported in WASM codegen"
      |calcit.core/try-decode-map-as#rejected-ref-decode-preserves-original "|unsupported: unsupported proc in WASM: ref"
      |calcit.core/try-decode-map-as#result-contract "|unsupported: try-decode-map-as is not yet supported in WASM codegen"
      |calcit.core/try-parse-cirru#result-method-contract "|unsupported: reaches `calcit.core/try-parse-cirru`: unsupported syntax in WASM: try"
      |calcit.core/try-parse-cirru-edn#nested-format-mode-roundtrip "|unsupported: E_WASM_EDN_TYPE: generic Number formatting is not yet exact in WASM; use an integer numeric refinement or defer this path"
      |calcit.core/try-parse-cirru-edn#result-method-contract "|unsupported: reaches `calcit.core/try-parse-cirru-edn`: unsupported syntax in WASM: try"
      |calcit.core/try-parse-cirru-edn#scalar-format-roundtrip "|unsupported: unsupported runtime quote value in WASM"
      |calcit.core/try-parse-cirru-edn-as#nested-list-failure-path "|parity: wrong result: expected 1, got 0"
      |calcit.core/try-parse-cirru-edn-as#parse-form-inside-typed-nth "|unsupported: parse-cirru-edn-as is not yet supported in WASM codegen"
      |calcit.core/try-parse-cirru-list#lexer-state-contract "|unsupported: reaches `calcit.core/try-parse-cirru-list`: unsupported syntax in WASM: try"
      |calcit.core/try-parse-cirru-list#result-method-contract "|unsupported: reaches `calcit.core/try-parse-cirru-list`: unsupported syntax in WASM: try"
      |calcit.core/try-parse-json#result-method-contract "|unsupported: reaches `calcit.core/try-parse-json`: unsupported syntax in WASM: try"
      |calcit.core/turn-str#accepts-proven-scalars "|unsupported: reaches `calcit.core/to-symbol`: unsupported proc in WASM: turn-symbol"
      |calcit.core/turn-symbol#returns-typed-symbol-from-string "|unsupported: unsupported proc in WASM: turn-symbol"
      |calcit.core/update#updates-existing-map-and-list-slots "|parity: collection result differs from native (assert= fails on the heap values)"
      |calcit.core/update-in#updates-collection-and-missing-paths "|unsupported: E_WASM_NIL_TYPE_EVIDENCE: nil? cannot distinguish nil from false or 0 for open type `dynamic`"
      |calcit.core/update-in#updates-existing-nested-leaf "|unsupported: E_WASM_NIL_TYPE_EVIDENCE: nil? cannot distinguish nil from false or 0 for open type `dynamic`"
      |calcit.core/wait-ms#positive-succeeds "|unsupported: reaches `calcit.core/wait-ms`: E_WASM_CAPABILITY: wait-ms is unavailable for the core WASM target"
      |calcit.core/wait-ms#rejects-fractional "|unsupported: reaches `calcit.core/wait-ms`: E_WASM_CAPABILITY: wait-ms is unavailable for the core WASM target"
      |calcit.core/wait-ms#rejects-out-of-range "|unsupported: reaches `calcit.core/wait-ms`: E_WASM_CAPABILITY: wait-ms is unavailable for the core WASM target"
      |calcit.core/wait-ms#zero-succeeds "|unsupported: reaches `calcit.core/wait-ms`: E_WASM_CAPABILITY: wait-ms is unavailable for the core WASM target"
      |calcit.test/fail#raises-errors "|unsupported: unsupported syntax in WASM: try"
      |calcit.test/is#rejects-falsey "|unsupported: unsupported syntax in WASM: try"
      |calcit.test/is-not=#rejects-equal-values "|unsupported: unsupported syntax in WASM: try"
      |calcit.test/is-throws#accepts-raised-errors "|unsupported: unsupported syntax in WASM: try"
      |calcit.test/is=#rejects-different-values "|unsupported: unsupported syntax in WASM: try"
      |calcit.test/throws?#detects-raised-errors "|unsupported: unsupported syntax in WASM: try"
      |calcit.test/throws?#detects-success "|unsupported: unsupported syntax in WASM: try"
  :wasi $ {}
    :tags $ {} $ :enum-definition-equality "|unsupported: first-class EnumDef creation requires &enum-def:new, rejected by the shared WASM codegen (#1863)"
    :tests $ {} (|calcit.core/&+#preserves-primitive-schema-in-local-binding "|unsupported: unsupported WASM expression: (&proc &+)")
      |calcit.core/&core-string-methods#excludes-file-effects "|unsupported: unsupported proc in WASM: &methods-of"
      |calcit.core/&doseq#applies-side-effects-per-item "|unsupported: unsupported proc in WASM: ref"
      |calcit.core/&doseq#types-range-index-in-body "|unsupported: unsupported proc in WASM: ref"
      |calcit.core/&enum:definition#nominal-definition-evidence "|unsupported: E_WASM_NIL_TYPE_EVIDENCE: `calcit.core/impl-traits` requires concrete argument types so nil can be distinguished from false and 0 (imported value …"
      |calcit.core/&extract-code-into-edn#rejects-runtime-only-values "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/&list:apply#preserves-homogeneous-function-result-types "|unsupported: nested fn/defn closure values are not yet supported in WASM codegen"
      |calcit.core/&list:assoc#rejects-out-of-range-index "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/&list:filter-pair#filters-key-value-pairs "|unsupported: E_WASM_CLOSURE_SPECIALIZATION: `calcit.core/&list:filter-pair` argument 2 is a closure but its static parameter contract is not callable"
      |calcit.core/&list:flatten#flattens-nested-lists-and-sets "|parity: collection result differs from native (assert= fails on the heap values)"
      |calcit.core/&list:map#typed-empty-accumulator "|parity: collection result differs from native (assert= fails on the heap values)"
      |calcit.core/&list:map-pair#maps-key-value-pairs "|unsupported: E_WASM_CLOSURE_SPECIALIZATION: `calcit.core/&list:map-pair` argument 2 is a closure but its static parameter contract is not callable"
      |calcit.core/&list:map-pair#uses-strict-named-call "|unsupported: E_WASM_CLOSURE_SPECIALIZATION: `calcit.core/&list:map-pair` argument 2 is a closure but its static parameter contract is not callable"
      |calcit.core/&list:nth#rejects-non-integer-index "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/&list:slice#rejects-fractional-bounds "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/&list:sort-by#sorts-by-function-key "|unsupported: E_WASI_COMMAND_INDIRECT: an indirect call may reach an unsupported host capability"
      |calcit.core/&map:destruct#exposes-pairs-and-folds "|parity: traps (unreachable) at runtime; native passes"
      |calcit.core/&map:filter-kv#filters-map-keys-and-values "|unsupported: unsupported proc in WASM: &map:fold-kv"
      |calcit.core/&map:filter-kv#preserves-typed-fields-and-effects "|unsupported: unsupported proc in WASM: ref"
      |calcit.core/&map:map#maps-map-pairs-directly "|parity: collection result differs from native (assert= fails on the heap values)"
      |calcit.core/&map:map#maps-pair-callback-with-key-and-value "|unsupported: unsupported proc in WASM: &map:fold-kv"
      |calcit.core/&map:map-list#maps-map-pairs-to-list "|parity: collection result differs from native (assert= fails on the heap values)"
      |calcit.core/&number:display-by#rejects-out-of-domain-values "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/&number:format#formats-decimal-places "|unsupported: unsupported proc in WASM: &number:format"
      |calcit.core/&number:format#rejects-digits-past-100 "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/&number:format#rounds-ties-away-from-zero "|unsupported: unsupported proc in WASM: &number:format"
      |calcit.core/&number:rem#rejects-zero-and-non-safe-integers "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/&str:escape#escapes-quoted-strings "|parity: wrong result: expected \"a \\\"\", got a \""
      |calcit.core/&str:pad-left#bounds-the-target-length "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/&str:pad-right#bounds-the-target-length "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/&str:slice#scalar-slice-invalid-evaluation "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/Option#direct-construction-preserves-value-and-failure "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/Option#matches-payloads-and-rejects-arity-mismatch "|parity: wrong result: expected 54, got 9"
      |calcit.core/Result#direct-construction-preserves-value-and-failure "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/add-watch!#registers-once-and-preserves-callback-order "|unsupported: unsupported proc in WASM: ref"
      |calcit.core/and#short-circuit-and-original-value-identity "|unsupported: unsupported proc in WASM: ref"
      |calcit.core/apply#preserves-evaluation-order "|unsupported: unsupported proc in WASM: ref"
      |calcit.core/apply#preserves-statement-evaluation-order "|unsupported: unsupported proc in WASM: ref"
      |calcit.core/assert-type#proven-list-payload "|parity: (xs .fold 0 +) does not produce 3"
      |calcit.core/assoc#preserves-struct-through-option-match "|unsupported: unsupported proc in WASM: &struct-def:new"
      |calcit.core/assoc#rejects-non-number-list-index "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/assoc-in#assocs-nested-maps-lists-and-nil-base "|unsupported: E_WASM_NIL_TYPE_EVIDENCE: nil? cannot distinguish nil from false or 0 for open type `dynamic`"
      |calcit.core/bit-and#rejects-non-i32-operands "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/case#literal-match-evaluates-once "|unsupported: unsupported proc in WASM: ref"
      |calcit.core/case-default#literal-patterns-use-match "|parity: wrong result: expected b, got n"
      |calcit.core/char-from-code#rejects-invalid-scalars "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/concat-dynamic#joins-open-lists "|parity: (count (concat-dynamic (assert-type ([] 1 2) (:: (quote List) (quote Dynamic))) (assert-type ([] 3) (:: (quote List) (quote Dynamic))))) does not produce 3"
      |calcit.core/contains-field?#checks-tag-field-and-missing-field "|unsupported: unsupported proc in WASM: &struct-def:new"
      |calcit.core/contains-in?#traverses-maps-lists-tags-and-enums "|parity: codegen fails: ::: expected tag as first arg, got: ([] (&syntax quote) 'quote)"
      |calcit.core/contains?#rejects-non-number-list-index "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/cos#evaluates-zero-and-half-turn "|unsupported: E_WASM_CAPABILITY: host capability `math/cos` is unavailable for this WASM target"
      |calcit.core/cos#satisfies-pythagorean-identity "|unsupported: E_WASM_CAPABILITY: host capability `math/sin` is unavailable for this WASM target"
      |calcit.core/count#empty-and-collection-counts "|parity: wrong result: expected 2, got 3"
      |calcit.core/data-view#classifies-symbol-struct-ref "|unsupported: unsupported runtime quote value in WASM"
      |calcit.core/data-view#classifies-values "|unsupported: E_WASM_NIL_TYPE_EVIDENCE: `calcit.core/data-view` requires concrete argument types so nil can be distinguished from false and 0"
      |calcit.core/data-view#exhaustive-view "|unsupported: E_WASM_NIL_TYPE_EVIDENCE: `calcit.core/data-view` requires concrete argument types so nil can be distinguished from false and 0"
      |calcit.core/data-view#lowered-match-agrees-with-enum-path "|unsupported: unsupported runtime quote value in WASM"
      |calcit.core/data-view#preserves-shallow-payloads "|unsupported: E_WASM_NIL_TYPE_EVIDENCE: `calcit.core/data-view` requires concrete argument types so nil can be distinguished from false and 0"
      |calcit.core/dbg#evaluates-once "|unsupported: unsupported proc in WASM: ref"
      |calcit.core/decode-map-as#decodes-inside-typed-first "|unsupported: decode-map-as is not yet supported in WASM codegen"
      |calcit.core/decode-map-as#preserves-operation-and-nested-error-path "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/ffi-response:resolve#method-preserves-capability-error "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/ffi-response:reject#method-preserves-capability-error "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/decode-map-as#decodes-struct-and-option "|unsupported: decode-map-as is not yet supported in WASM codegen"
      |calcit.core/decode-map-as#nested-struct-option "|unsupported: decode-map-as is not yet supported in WASM codegen"
      |calcit.core/decode-map-as#preserves-dynamic-and-prewrapped-option "|unsupported: decode-map-as is not yet supported in WASM codegen"
      |calcit.core/defstruct#local-definition-constructs-directly "|unsupported: unsupported proc in WASM: &struct-def:new"
      |calcit.core/deftrait#requires-head-accepts-bare-and-quoted "|unsupported: unsupported syntax in WASM: macroexpand"
      |calcit.core/deref#named-call-preserves-ref-payload "|unsupported: unsupported proc in WASM: ref"
      |calcit.core/destruct-map#splits-entry-and-remainder "|parity: collection result differs from native (assert= fails on the heap values)"
      |calcit.core/dissoc#empty-list-spread-keeps-map "|parity: codegen fails: invalid core WebAssembly module: type mismatch: values remaining on stack at end of block"
      |calcit.core/dissoc#explicitly-converts-set-keys "|parity: collection result differs from native (assert= fails on the heap values)"
      |calcit.core/dissoc#fixed-call-direct-evaluates-arguments-once "|unsupported: unsupported proc in WASM: ref"
      |calcit.core/dissoc#fixed-call-spread-evaluates-arguments-once "|unsupported: unsupported proc in WASM: ref"
      |calcit.core/dissoc#local-function-list-spread "|parity: traps (unreachable) at runtime; native passes"
      |calcit.core/dissoc#preserves-heterogeneous-list-spread "|parity: collection result differs from native (assert= fails on the heap values)"
      |calcit.core/dissoc#preserves-unspread-arguments "|parity: codegen fails: invalid core WebAssembly module: type mismatch: values remaining on stack at end of block"
      |calcit.core/dissoc#rejects-unsupported-receiver "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/dissoc#removes-list-index-by-kind-dispatch "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/dissoc#removes-multiple-map-keys "|parity: collection result differs from native (assert= fails on the heap values)"
      |calcit.core/dissoc#spreads-list-keys "|parity: collection result differs from native (assert= fails on the heap values)"
      |calcit.core/dissoc#supports-multiple-list-spreads "|parity: collection result differs from native (assert= fails on the heap values)"
      |calcit.core/dissoc-in#dissocs-nested-maps-and-list-indexes "|unsupported: E_WASM_NIL_TYPE_EVIDENCE: `calcit.core/assoc` requires concrete argument types so nil can be distinguished from false and 0"
      |calcit.core/do#supports-multiple-fn-body-without-do "|unsupported: unsupported proc in WASM: ref"
      |calcit.core/do#supports-multiple-let-body-without-do "|unsupported: unsupported proc in WASM: ref"
      |calcit.core/ffi-task:cancel#checked-unit-preserves-actual-value "|unsupported: decode-map-as is not yet supported in WASM codegen"
      |calcit.core/ffi-task:cancel#checked-unit-rejects-nil "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/ffi-task:cancel#checked-unit-rejects-number "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/ffi-task:cancel#checked-unit-rejects-string "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/ffi-task:cancel#default-method-preserves-capability-error "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/ffi-task:cancel-with#explicit-method-preserves-capability-error "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/ffi-task:cancel-with#reason-error-propagates-before-host-call "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/ffi-task:cancel-with#reason-evaluates-once-before-host-error "|unsupported: unsupported proc in WASM: ref"
      |calcit.core/ffi:response#effect-method-contract "|unsupported: E_WASM_CLOSURE_SPECIALIZATION: closure `resolve` escapes a statically specialized call"
      |calcit.core/ffi:task#effect-method-contract "|unsupported: E_WASM_CLOSURE_SPECIALIZATION: closure `cancel` escapes a statically specialized call"
      |calcit.core/filter-map-kv#preserves-captured-generic-relations "|unsupported: reaches `calcit.core/to-tag`: E_WASM_TAG_CONVERSION: turn-tag/to-tag requires runtime tag interning, which WASM does not support"
      |calcit.core/filter-map-kv#preserves-collision-iterator-last-value "|unsupported: unsupported proc in WASM: &map:fold-kv"
      |calcit.core/filter-map-kv#preserves-generic-callback-map-types "|unsupported: reaches `calcit.core/to-tag`: E_WASM_TAG_CONVERSION: turn-tag/to-tag requires runtime tag interning, which WASM does not support"
      |calcit.core/filter-map-kv#skips-empty-and-propagates-failure "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/fold#receiver-method "|parity: (([] 1 2 3) .fold 0 +) does not produce 6"
      |calcit.core/fold-while#stops-calling-reducer-after-break "|unsupported: unsupported proc in WASM: ref"
      |calcit.core/foldl-compare#typed-number-exits "|unsupported: recur in a statically specialized closure is not yet supported in WASM codegen"
      |calcit.core/foldl-shortcut#returns-shortcut-accumulator "|parity: codegen fails: ::: expected tag as first arg, got: ([] (&proc &=) 'x 2)"
      |calcit.core/foldr-shortcut#returns-shortcut-accumulator "|parity: codegen fails: ::: expected tag as first arg, got: ([] (&proc &=) 'x 2)"
      |calcit.core/format-cirru#formats-nested-lines "|unsupported: unsupported proc in WASM: format-cirru"
      |calcit.core/format-cirru-edn#formats-basic-edn-values "|unsupported: unsupported runtime quote value in WASM"
      |calcit.core/format-cirru-one-liner#formats-simple-form-on-one-line "|unsupported: unsupported proc in WASM: format-cirru-one-liner"
      |calcit.core/format-cirru-one-liner#rejects-spread-non-list "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/format-to-lisp#distinguishes-simple-and-quoted-strings "|unsupported: unsupported runtime format-to-lisp in WASM: requires a statically quoted expression"
      |calcit.core/format-to-lisp#formats-runtime-number "|unsupported: unsupported runtime format-to-lisp in WASM: requires a statically quoted expression"
      |calcit.core/fs:path#fs-path-contract "|unsupported: reaches `calcit.core/fs-path:write-text`: E_WASI_COMMAND_CAPABILITY: `&fs-write-text` needs a reachable WASI 0.3 filesystem effect"
      |calcit.core/fs:path#write-text-effect-contract "|unsupported: reaches `calcit.core/fs-path:write-text`: E_WASI_COMMAND_CAPABILITY: `&fs-write-text` needs a reachable WASI 0.3 filesystem effect"
      |calcit.core/get#reads-runtime-struct-from-open-value "|unsupported: unsupported runtime quote value in WASM"
      |calcit.core/get#reads-tag-keys-via-postfix "|unsupported: unsupported method in WASM: .a"
      |calcit.core/get#typed-nested-get-inside-when "|unsupported: unsupported proc in WASM: ref"
      |calcit.core/get-char-code#rejects-multiple-characters "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/get-in#reads-nested-open-map-payload "|unsupported: E_WASM_NIL_TYPE_EVIDENCE: `calcit.core/get-in` requires concrete argument types so nil can be distinguished from false and 0"
      |calcit.core/group-by#groups-list-by-derived-key "|parity: codegen fails: inline closure expects 2 argument(s), got 1"
      |calcit.core/hint-fn#async-tail-return-contract "|unsupported: E_WASM_CLOSURE_SPECIALIZATION: closure `forward` escapes a statically specialized call"
      |calcit.core/hint-fn#callable-return-contract "|unsupported: unsupported call head in WASM: ([] 'keep 'pass-number)"
      |calcit.core/hint-fn#checked-number-to-concrete-call "|unsupported: try-decode-map-as is not yet supported in WASM codegen"
      |calcit.core/hint-fn#literal-spread-call-contract "|parity: codegen fails: F64Add expects 2 args, got 1"
      |calcit.core/hint-fn#open-element-classified-before-payload "|unsupported: E_WASI_COMMAND_DEPENDENCY: calcit.core/data-view requires concrete argument types so nil can be distinguished from false and 0 (E_WASM_NIL_TYPE_EVIDENCE)"
      |calcit.core/hint-fn#raise-only-return-contract "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/identity#preserves-generic-schema-for-local-binding "|unsupported: E_WASI_COMMAND_INDIRECT: an indirect call may reach an unsupported host capability"
      |calcit.core/if#condition-and-selected-branch-errors-propagate "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/if#condition-evaluates-once-and-only-one-branch-runs "|unsupported: unsupported proc in WASM: ref"
      |calcit.core/if#direct-unsafe-bool-keeps-runtime-truthiness "|unsupported: E_WASM_UNSUPPORTED_JS_FFI: unsafe-coerce cannot preserve value identity in the current scalar WASM ABI"
      |calcit.core/includes?#checks-open-map-values-and-set-members "|unsupported: E_WASM_TRAIT_TYPE_EVIDENCE: a List mixing Map and Set receivers has no concrete element type for the open includes? dispatch"
      |calcit.core/join-string#renders-numbers-duplicates-and-empty-list "|parity: wrong result: expected 1-2-3, got 1-1-1"
      |calcit.core/keys-non-nil#omits-nil-map-values "|unsupported: E_WASM_CALL_SPECIALIZATION: recursive specialization of `calcit.core/&section-by-loop` is not supported"
      |calcit.core/last#rejects-invalid-string-indices "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/loop#preserves-standalone-loop-effects "|unsupported: unsupported proc in WASM: ref"
      |calcit.core/map#maps-map-pairs "|parity: collection result differs from native (assert= fails on the heap values)"
      |calcit.core/map#maps-over-sets "|unsupported: E_WASI_COMMAND_INDIRECT: an indirect call may reach an unsupported host capability"
      |calcit.core/map-entries#infers-sort-comparator-fields "|unsupported: reaches `calcit.core/map-entries`: unsupported proc in WASM: &map:fold-kv"
      |calcit.core/map-entries#preserves-key-value-types "|unsupported: reaches `calcit.core/map-entries`: unsupported proc in WASM: &map:fold-kv"
      |calcit.core/map-entries#survives-sort-and-indexing "|unsupported: E_WASI_COMMAND_INDIRECT: an indirect call may reach an unsupported host capability"
      |calcit.core/map-indexed#preserves-open-payload-with-index "|parity: collection result differs from native (assert= fails on the heap values)"
      |calcit.core/map-kv#skips-nil-results "|parity: collection result differs from native (assert= fails on the heap values)"
      |calcit.core/map-list-kv#collects-typed-key-value-results "|unsupported: unsupported proc in WASM: &map:fold-kv"
      |calcit.core/map-list-kv#preserves-iteration-effects-and-failure "|unsupported: unsupported proc in WASM: ref"
      |calcit.core/map-list-kv#preserves-nominal-key-value-fields "|unsupported: unsupported proc in WASM: &map:fold-kv"
      |calcit.core/mapcat#flat-map-keeps-order-type-and-callback-count "|unsupported: unsupported proc in WASM: ref"
      |calcit.core/merge#combines-maps-left-to-right "|unsupported: E_WASM_CALL_SPECIALIZATION: recursive specialization of `calcit.core/&section-by-loop` is not supported"
      |calcit.core/merge-non-nil#keeps-existing-values-for-nil "|unsupported: E_WASM_CALL_SPECIALIZATION: recursive specialization of `calcit.core/&section-by-loop` is not supported"
      |calcit.core/monotonic-time-ms#keeps-monotonic-milliseconds "|unsupported: E_WASI_COMMAND_CAPABILITY: `monotonic-time-ms` needs WASI 0.3 clocks lowering"
      |calcit.core/number->int8#checks-boundaries-and-type "|unsupported: parse-cirru-edn-as is not yet supported in WASM codegen"
      |calcit.core/option:let#short-circuits-none "|unsupported: E_WASM_CALL_SPECIALIZATION: recursive specialization of `calcit.core/option:and-then` is not supported"
      |calcit.core/or#short-circuit-and-original-value-identity "|unsupported: unsupported proc in WASM: ref"
      |calcit.core/parse-cirru#returns-cirru-quote-tree "|unsupported: unsupported proc in WASM: parse-cirru"
      |calcit.core/parse-cirru-edn#parses-enums-comments-and-quoted-code "|unsupported: unsupported proc in WASM: parse-cirru-edn"
      |calcit.core/parse-cirru-list#returns-nested-text-lines "|unsupported: unsupported proc in WASM: parse-cirru-list"
      |calcit.core/parse-float#parses-nonfinite-spellings "|unsupported: reaches `calcit.core/parse-float`: E_WASM_NIL_TYPE_EVIDENCE: nil? cannot distinguish nil from a zero-valued Optional<:number> payload in the current …"
      |calcit.core/parse-float#reports-invalid-number-source "|unsupported: reaches `calcit.core/parse-float`: E_WASM_NIL_TYPE_EVIDENCE: nil? cannot distinguish nil from a zero-valued Optional<:number> payload in the current …"
      |calcit.core/parse-float#result-method-contract "|unsupported: reaches `calcit.core/parse-float`: E_WASM_NIL_TYPE_EVIDENCE: nil? cannot distinguish nil from a zero-valued Optional<:number> payload in the current …"
      |calcit.core/parse-float#wraps-number-or-source-error "|unsupported: reaches `calcit.core/parse-float`: E_WASM_NIL_TYPE_EVIDENCE: nil? cannot distinguish nil from a zero-valued Optional<:number> payload in the current …"
      |calcit.core/pow#follows-ieee-for-unit-base "|unsupported: E_WASM_CAPABILITY: host capability `math/pow` is unavailable for this WASM target"
      |calcit.core/pow#raises-to-power "|unsupported: E_WASM_CAPABILITY: host capability `math/pow` is unavailable for this WASM target"
      |calcit.core/quote#function-tail-values "|unsupported: unsupported runtime quote value in WASM"
      |calcit.core/quote#nested-tail-and-expression-contexts "|unsupported: unsupported runtime quote value in WASM"
      |calcit.core/quote#preserves-non-evaluation-and-effects "|unsupported: unsupported proc in WASM: ref"
      |calcit.core/range#handles-negative-fractional-and-overflow "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/range#rejects-oversized-length "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/range#rejects-zero-step "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/range-bothway#creates-symmetric-and-offset-ranges "|parity: collection result differs from native (assert= fails on the heap values)"
      |calcit.core/read-dir#preserves-missing-directory-failure "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/read-dir#preserves-one-and-two-argument-directory-reads "|parity: codegen fails: unknown function: calcit.core/read-dir"
      |calcit.core/read-file#preserves-file-read-alias "|parity: codegen fails: unknown function: calcit.core/read-file"
      |calcit.core/read-file#preserves-missing-file-failure "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/reduce#reduces-list-from-initial-value "|parity: wrong result: expected 14, got 2"
      |calcit.core/ref#creates-typed-local-ref "|unsupported: unsupported proc in WASM: ref"
      |calcit.core/remove-watch!#rejects-missing-key-without-repeating-effect "|unsupported: unsupported proc in WASM: ref"
      |calcit.core/recur#recurs-from-try-and-match-tail-positions "|unsupported: E_WASI_COMMAND_DEPENDENCY: unsupported syntax in WASM: try; the match assertion is also replayed separately by recurs-from-match-tail-position"
      |calcit.core/result:map-err#typed-method-selects-only-matching-branch "|unsupported: E_WASI_COMMAND_DEPENDENCY reaches `calcit.core/to-tag`: E_WASM_TAG_CONVERSION: runtime tag interning is unsupported; maps-error-to-inferred-number replays the supported method path"
      |calcit.core/rest#rejects-non-sequence "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/reset!#empty-initializer-needs-explicit-payload "|unsupported: E_WASI_COMMAND_DEPENDENCY: unsupported proc in WASM: ref"
      |calcit.core/reset!#nested-assignment-returns-final-value "|unsupported: unsupported proc in WASM: ref"
      |calcit.core/reset!#returns-assigned-scalar "|unsupported: unsupported proc in WASM: ref"
      |calcit.core/chunks#splits-list-into-fixed-sections "|unsupported: E_WASM_CALL_SPECIALIZATION: recursive specialization of `calcit.core/&section-by-loop` is not supported"
      |calcit.core/chunks#keeps-short-lists-whole "|unsupported: E_WASM_CALL_SPECIALIZATION: recursive specialization of `calcit.core/&section-by-loop` is not supported"
      |calcit.core/chunks#empty-list-has-no-sections "|unsupported: E_WASM_CALL_SPECIALIZATION: recursive specialization of `calcit.core/&section-by-loop` is not supported"
      |calcit.core/section-by#forwards-to-chunks "|unsupported: E_WASM_CALL_SPECIALIZATION: recursive specialization of `calcit.core/&section-by-loop` is not supported"
      |calcit.core/secure-random-bytes#rejects-invalid-length "|unsupported: reaches `calcit.core/secure-random-bytes`: E_WASI_COMMAND_CAPABILITY: `&secure-random-bytes` needs WASI 0.3 random lowering"
      |calcit.core/secure-random-bytes#returns-buffer "|unsupported: reaches `calcit.core/secure-random-bytes`: E_WASI_COMMAND_CAPABILITY: `&secure-random-bytes` needs WASI 0.3 random lowering"
      |calcit.core/sin#evaluates-zero-and-quarter-turn "|unsupported: E_WASM_CAPABILITY: host capability `math/sin` is unavailable for this WASM target"
      |calcit.core/sort#orders-list-with-default-comparator "|unsupported: &list:sort in WASM requires a list and an explicit 2-argument comparator"
      |calcit.core/sort#sorts-nan-after-numbers "|unsupported: &list:sort in WASM requires a list and an explicit 2-argument comparator"
      |calcit.core/starts-with?#supports-tag-and-string-prefixes "|unsupported: E_WASM_UNSUPPORTED_JS_FFI: unsafe-coerce cannot preserve value identity in the current scalar WASM ABI"
      |calcit.core/str#omits-nil-and-renders-enums "|parity: wrong result: expected (%:: _ :a |世界 \"|海 洋\"), got (:: :a |世界 \"|海 洋\")"
      |calcit.core/swap!#expanded-result-is-the-assigned-value "|unsupported: unsupported proc in WASM: ref"
      |calcit.core/to-lispy-string#distinguishes-display-from-lisp-format "|unsupported: unsupported runtime format-to-lisp in WASM: requires a statically quoted expression"
      |calcit.core/to-string#converts-finite-scalars "|unsupported: reaches `calcit.core/to-symbol`: unsupported proc in WASM: turn-symbol"
      |calcit.core/to-string#map-entry-tag-method-contract "|unsupported: nested fn/defn closure values are not yet supported in WASM codegen"
      |calcit.core/to-string#scalar-method-contract "|unsupported: reaches `calcit.core/to-symbol`: unsupported proc in WASM: turn-symbol"
      |calcit.core/to-symbol#converts-string-to-symbol "|unsupported: reaches `calcit.core/to-symbol`: unsupported proc in WASM: turn-symbol"
      |calcit.core/to-tag#converts-string-to-tag "|unsupported: reaches `calcit.core/to-tag`: E_WASM_TAG_CONVERSION: turn-tag/to-tag requires runtime tag interning, which WASM does not support"
      |calcit.core/try#passes-error-message-to-handler "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/try#returns-body-on-success "|unsupported: unsupported syntax in WASM: try"
      |calcit.core/try-decode-map-as#decoded-ref-keeps-original-alias-open "|unsupported: unsupported proc in WASM: ref"
      |calcit.core/try-decode-map-as#parsed-open-value-deep-rejection "|unsupported: try-decode-map-as is not yet supported in WASM codegen"
      |calcit.core/try-decode-map-as#parsed-open-value-deep-success "|unsupported: try-decode-map-as is not yet supported in WASM codegen"
      |calcit.core/try-decode-map-as#rejected-ref-decode-preserves-original "|unsupported: unsupported proc in WASM: ref"
      |calcit.core/try-decode-map-as#result-contract "|unsupported: try-decode-map-as is not yet supported in WASM codegen"
      |calcit.core/try-parse-cirru#result-method-contract "|unsupported: reaches `calcit.core/try-parse-cirru`: unsupported syntax in WASM: try"
      |calcit.core/try-parse-cirru-edn#nested-format-mode-roundtrip "|unsupported: E_WASM_EDN_TYPE: generic Number formatting is not yet exact in WASM; use an integer numeric refinement or defer this path"
      |calcit.core/try-parse-cirru-edn#result-method-contract "|unsupported: reaches `calcit.core/try-parse-cirru-edn`: unsupported syntax in WASM: try"
      |calcit.core/try-parse-cirru-edn#scalar-format-roundtrip "|unsupported: unsupported runtime quote value in WASM"
      |calcit.core/try-parse-cirru-edn-as#nested-list-failure-path "|parity: (message .includes? \"|[0][1]\") does not produce 1"
      |calcit.core/try-parse-cirru-edn-as#parse-form-inside-typed-nth "|unsupported: parse-cirru-edn-as is not yet supported in WASM codegen"
      |calcit.core/try-parse-cirru-list#lexer-state-contract "|unsupported: reaches `calcit.core/try-parse-cirru-list`: unsupported syntax in WASM: try"
      |calcit.core/try-parse-cirru-list#result-method-contract "|unsupported: reaches `calcit.core/try-parse-cirru-list`: unsupported syntax in WASM: try"
      |calcit.core/try-parse-json#result-method-contract "|unsupported: reaches `calcit.core/try-parse-json`: unsupported syntax in WASM: try"
      |calcit.core/turn-str#accepts-proven-scalars "|unsupported: reaches `calcit.core/to-symbol`: unsupported proc in WASM: turn-symbol"
      |calcit.core/turn-symbol#returns-typed-symbol-from-string "|unsupported: unsupported proc in WASM: turn-symbol"
      |calcit.core/update#updates-existing-map-and-list-slots "|parity: collection result differs from native (assert= fails on the heap values)"
      |calcit.core/update-in#updates-collection-and-missing-paths "|unsupported: E_WASM_NIL_TYPE_EVIDENCE: nil? cannot distinguish nil from false or 0 for open type `dynamic`"
      |calcit.core/update-in#updates-existing-nested-leaf "|unsupported: E_WASM_NIL_TYPE_EVIDENCE: nil? cannot distinguish nil from false or 0 for open type `dynamic`"
      |calcit.core/wait-ms#positive-succeeds "|unsupported: reaches `calcit.core/wait-ms`: E_WASI_COMMAND_CAPABILITY: `&wait-ms` needs WASI 0.3 clocks lowering"
      |calcit.core/wait-ms#rejects-fractional "|unsupported: reaches `calcit.core/wait-ms`: E_WASI_COMMAND_CAPABILITY: `&wait-ms` needs WASI 0.3 clocks lowering"
      |calcit.core/wait-ms#rejects-out-of-range "|unsupported: reaches `calcit.core/wait-ms`: E_WASI_COMMAND_CAPABILITY: `&wait-ms` needs WASI 0.3 clocks lowering"
      |calcit.core/wait-ms#zero-succeeds "|unsupported: reaches `calcit.core/wait-ms`: E_WASI_COMMAND_CAPABILITY: `&wait-ms` needs WASI 0.3 clocks lowering"
      |calcit.test/fail#raises-errors "|unsupported: unsupported syntax in WASM: try"
      |calcit.test/is#rejects-falsey "|unsupported: unsupported syntax in WASM: try"
      |calcit.test/is-not=#rejects-equal-values "|unsupported: unsupported syntax in WASM: try"
      |calcit.test/is-throws#accepts-raised-errors "|unsupported: unsupported syntax in WASM: try"
      |calcit.test/is=#rejects-different-values "|unsupported: unsupported syntax in WASM: try"
      |calcit.test/throws?#detects-raised-errors "|unsupported: unsupported syntax in WASM: try"
      |calcit.test/throws?#detects-success "|unsupported: unsupported syntax in WASM: try"
